### ISSUE TITLE
unable to implementing ACL

### ISSUE THREAD

**Issue by parvindersingh0722** [jamesbak/recursive_acl#1]
Hi James, Thanks for sharing the script.

I have updated the variable Such as clientId, clientSecret, tenant, accountName, container and 
$absoluteAcl = "user:Pa.Sin@abc.com:rwx,default:user:Pa.Sin@dac.nsw.gov.au:rwx"
and try to run the script on Cloudshell, however, it didn't apply acl on container and rootDir.

Your help will be much appreciated

**Comment by jamesbak** [comment]
Thanks for the catch @parvindersingh0722. I have updated the script with a fix to address including the root directory.
